### ISSUE TITLE
Error npm start

### ISSUE THREAD

**Issue by cristiansot** [cristiansot/React-App-V2#15]
<img width="1264" alt="Captura de Pantalla 2023-12-21 a la(s) 11 53 37" src="https://github.com/cristiansot/React-App-V2/assets/26008003/56592f19-6b8b-41e2-b7a7-9fa66829b881">

I have a problem with this issue

**Comment by Marwa-502** [comment]
I also had issues with this. Let me know when you have time and we can go into a slack huddle to try and solve it together.

**Comment by cristiansot** [comment]
I resolved, thanks
