### ISSUE TITLE
postActivity function - mockAPI is not taking ID created by uuid on POST request 

### ISSUE THREAD

**Issue by NovitaHamilton** [cristiansot/React-App-V2#4]
mockAPI is not taking ID created by uuid on POST request that's passed on correctly.
It's instead generating it's own ID

Example of data passed on:

activity: "Hiking"
caloriesBurned: 890
date: "2023-12-05"
duration: 120
id: "af073188-d4a0-4684-b867-6a8685b3b839"
intensity: "High"

Result in mockAPI:

  "duration": 120,
    "date": "2023-12-05",
    "intensity": "High",
    "calories": 23,
    "activity": "Hiking",
    "id": "6",
    "caloriesBurned": 890

**Comment by cristiansot** [comment]
Hello, it is not necessary to use the uuid library, since mockapi creates its own id, you must keep in mind that it is necessary to create a function so as not to overwrite the dates, greetings

**Comment by NovitaHamilton** [comment]
Hi @cristiansot, yes I'm aware that mockAPI creates its own ID. But I'm just curious why it's not passing the ID on POST request, since I have done that in the past with another project. This was just something I wanted to look at on the side, for learning purposes. Hence, I assigned the ticket to myself. But thanks for checking.

**Comment by cristiansot** [comment]
You can overwrite the id, I used the following code to do it in the passing assigment:

    const newBook = {
      id: uuidv4(), 
    };

**Comment by NovitaHamilton** [comment]
Yes, that's what I did. The data passed during the POST call is correct, but it's still overwritten by mockAPI. The response returns the ID created by mockAPI. That's where the issue is.
But don't worry about it now. This is not urgent and something I want to look up later.
